name: Deploy Laravel

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --no-progress --prefer-dist --no-interaction

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM Dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Build Assets
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to server
        uses: up9cloud/action-rsync@master
        continue-on-error: true
        env:
          HOST: ${{ secrets.SSH_HOST }}
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USER }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TARGET: ${{ secrets.DEPLOY_PATH }}
          ARGS: "-avz --exclude=node_modules --exclude=vendor --exclude=storage --exclude=public/storage --exclude=.env"

      - name: Clean unused files
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git clean -fd

      - name: Install production dependencies
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            npm ci --production --prefer-offline --no-audit --progress=false
            composer install --no-dev --optimize-autoloader --no-progress --prefer-dist --no-interaction

      - name: Database Migrations and Seed
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            php artisan migrate
            php artisan db:seed --class=DatabaseSeeder
