name: Linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: npm ci

      - name: Lint Frontend
        run: npm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[BOT] 🔧 Auto lint fix"
          push_options: ""
          skip_dirty_check: false
          branch: ${{ github.event.pull_request.head.ref }}
